


#    func_print_head "get frontend zip file"
#    curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>$log_file
#    func_status_check $?
#
#    func_print_head "remove old content"
#    cd /usr/share/nginx/html &>>$log_file
#    func_status_check $?
#
#    func_print_head "unzip content"
#    unzip /tmp/frontend.zip &>>$log_file
#    func_status_check $?
#
#    func_print_head "start nginx service"
#    systemctl restart nginx &>>$log_file
#    systemctl enable nginx &>>$log_file
#    func_status_check $?

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copy roboshop conf file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: remove nginx html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: get frontend zip file
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes