
#    func_print_head "copy roboshop conf file"
#    cp roboshop.conf /etc/nginx/default.d/roboshop.conf &>>$log_file
#    func_status_check $?
#
#    func_print_head "remove nginx html content"
#    rm -rf /usr/share/nginx/html/* &>>$log_file
#    func_status_check $?
#
#    func_print_head "get frontend zip file"
#    curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>$log_file
#    func_status_check $?
#
#    func_print_head "remove old content"
#    cd /usr/share/nginx/html &>>$log_file
#    func_status_check $?
#
#    func_print_head "unzip content"
#    unzip /tmp/frontend.zip &>>$log_file
#    func_status_check $?
#
#    func_print_head "start nginx service"
#    systemctl restart nginx &>>$log_file
#    systemctl enable nginx &>>$log_file
#    func_status_check $?

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: copy roboshop conf file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

