- name: Copy elastic repofile
  ansible.builtin.template:
    scr: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed
