labels:
  - { tag: Name, label: name }
  - { tag: env, label: env }
  - { tag: component, label: component }

components:
  - { name: frontend, service_name: nginx }
  - { name: catalogue, service_name: catalogue }
  - { name: user, service_name: user }
  - { name: cart, service_name: cart }
  - { name: shipping, service_name: shipping }
  - { name: payment, service_name: payment }