- name: Install maven
  ansible.builtin.yum:
    name: maven

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install Maven Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include systemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
