groups:
  - name: CPU Utilization for Ec2-nodes
    rules:
      - alert: HighCPUUtilization
        expr: 100 - (avg by(component,env,instance,name) (rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100)) < 30
        for: 1m
        labels:
          severity: page
        annotations:
          summary: High CPU Alert